[build]
  base = "client"
  publish = "dist"
  command = "npm install --legacy-peer-deps && npm run build"

# Redirects and headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variable inheritance
[build.environment]
  NODE_VERSION = "18"

# Cache control for better performance
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
